[tool.poetry]
name = "formatter"
version = "0.1.0"
description = ""
authors = ["hewimetall <git@metal.com>"]

[tool.poetry.dependencies]
python = "^3.8"
bbcode = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
